name:                aoc2020
version:             1.1.0.0
github:              "StephenSwat/aoc2020-hs"
license:             Unlicense
author:              "Stephen Nicholas Swatman"
maintainer:          "stephen@v25.nl"

dependencies:
  - base >= 4.7 && < 5
  - regex-pcre
  - containers == 0.6.2.1
  - split == 0.2.3.4
  - lens == 4.18.1
  - relude == 0.7.0.0
  - mtl == 2.2.2

executables:
  aoc2020:
    main:                Main.hs
    source-dirs:         src
